---
# php
php_webserver_daemon: "nginx"
php_enable_php_fpm: true
php_packages:
  - php7.0-common
  - php7.0-cli
  - php7.0-dev
  - php7.0-fpm
  - libpcre3-dev
  - php7.0-gd
  - php7.0-curl
  - php7.0-imap
  - php7.0-json
  - php7.0-opcache
  - php7.0-xml
  - php7.0-mbstring
  - php-sqlite3
  - php-apcu
  - php7.0-mcrypt
  - php-mysql
  - php7.0-readline
  - php7.0-zip
  - php7.0-intl
  - php7.0-bcmath
  - build-essential

# node.js
node_version: 6.x
nodejs_npm_global_packages:
  - name: gulp-cli
  - name: bower
  - name: yarn
  
# mysql
mysql_root_password: root

mysql_databases:
  - name: dscars


# composer
composer_home_path: /home/vagrant/.composer
composer_home_owner: vagrant
composer_home_group: vagrant
composer_global_packages:
  - { name: phpunit/phpunit }

# php-fpm
php_fpm_pool_user: vagrant
php_fpm_pool_group: vagrant

# xdebug
php_xdebug_cli_enable: 1
php_xdebug_remote_enable: "true"
php_xdebug_remote_connect_back: "true"
php_xdebug_remote_host: localhost
php_xdebug_remote_port: "9000"
php_xdebug_idekey: debug
php_xdebug_remote_autostart: 1 

# nginx
nginx_user: vagrant
nginx_group: vagrant